name: Profile
favicon: null
layout_spectrum: 0.06954648229293525
typography_spectrum: 0.7900580973364413
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.09553236910142004
  lightness: 0.37879460072144866
  saturation: 0.9514521562959999
  rhythmicContrast: 0.5107560402248055
purpose: []
